// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package ratelimiter

import "time"

// Options should use NewOptions to initialize it
type Options struct {
	per   time.Duration
	Slack int
}

// NewOptions new Options
func NewOptions(opts ...Option) *Options {
	cc := newDefaultOptions()
	for _, opt := range opts {
		opt.Apply(cc)
	}
	if watchDogOptions != nil {
		watchDogOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option
func (cc *Options) ApplyOption(opts ...Option) {
	for _, opt := range opts {
		opt.Apply(cc)
	}
}

// OptionFunc option func
type Option interface {
	Apply(cc *Options)
}

var _ Option = OptionFunc(nil)

type OptionFunc func(cc *Options)

func (f OptionFunc) Apply(cc *Options) {
	f(cc)
}

// WithPer option func for filed per
func WithPer(v time.Duration) OptionFunc {
	return func(cc *Options) {
		cc.per = v
	}
}

// WithSlack option func for filed Slack
func WithSlack(v int) OptionFunc {
	return func(cc *Options) {
		cc.Slack = v
	}
}

// InstallOptionsWatchDog the installed func will called when NewOptions  called
func InstallOptionsWatchDog(dog func(cc *Options)) { watchDogOptions = dog }

// watchDogOptions global watch dog
var watchDogOptions func(cc *Options)

// setOptionsDefaultValue default Options value
func setOptionsDefaultValue(cc *Options) {
	for _, opt := range [...]OptionFunc{
		WithPer(time.Second),
		WithSlack(10),
	} {
		opt(cc)
	}
}

// newDefaultOptions new default Options
func newDefaultOptions() *Options {
	cc := &Options{}
	setOptionsDefaultValue(cc)
	return cc
}

// all getter func
func (cc *Options) GetPer() time.Duration { return cc.per }
func (cc *Options) GetSlack() int         { return cc.Slack }

// OptionsVisitor visitor interface for Options
type OptionsVisitor interface {
	GetPer() time.Duration
	GetSlack() int
}

// OptionsInterface visitor + ApplyOption interface for Options
type OptionsInterface interface {
	OptionsVisitor
	ApplyOption(...Option)
}
