// Code generated by tools. DO NOT EDIT.
package geom

import (
	. "github.com/smartystreets/goconvey/convey"
	"testing"
)

func TestRectangleInt32_SnakeRange(t *testing.T) {
	HelixRectRangeFromCenterAndMarginInt32(PtInt32(2, 2), 2, func(p PointInt32) bool {
		t.Log(p.X, p.Y)
		return true
	})

	Convey("test intersection with line", t, func() {
		rect := RectInt32(0, 0, 3, 3)
		So(rect.IntersectionWithLine(PtInt32(1, 0), PtInt32(1, 4)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(1, 0), PtInt32(1, 3)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(1, 0), PtInt32(1, 2)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(1, 0), PtInt32(1, 1)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(2, 0), PtInt32(2, 2)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(0, 2), PtInt32(1, 2)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(0, 1), PtInt32(3, 1)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt32(0, 0), PtInt32(0, 1)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(0, 0), PtInt32(0, 2)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(0, 0), PtInt32(0, 3)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(0, 0), PtInt32(0, 4)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(0, 0), PtInt32(1, 0)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(0, 0), PtInt32(2, 0)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(1, 4), PtInt32(2, 4)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(0, 3), PtInt32(3, 3)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt32(1, 3), PtInt32(2, 4)), ShouldBeFalse) // should be false
	})
}
