// Code generated by tools. DO NOT EDIT.
package geom

import (
	. "github.com/smartystreets/goconvey/convey"
	"testing"
)

func TestRectangleInt64_SnakeRange(t *testing.T) {
	HelixRectRangeFromCenterAndMarginInt64(PtInt64(2, 2), 2, func(p PointInt64) bool {
		t.Log(p.X, p.Y)
		return true
	})

	Convey("test intersection with line", t, func() {
		rect := RectInt64(0, 0, 3, 3)
		So(rect.IntersectionWithLine(PtInt64(1, 0), PtInt64(1, 4)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(1, 0), PtInt64(1, 3)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(1, 0), PtInt64(1, 2)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(1, 0), PtInt64(1, 1)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(2, 0), PtInt64(2, 2)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(0, 2), PtInt64(1, 2)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(0, 1), PtInt64(3, 1)), ShouldBeTrue)  // should be true
		So(rect.IntersectionWithLine(PtInt64(0, 0), PtInt64(0, 1)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(0, 0), PtInt64(0, 2)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(0, 0), PtInt64(0, 3)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(0, 0), PtInt64(0, 4)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(0, 0), PtInt64(1, 0)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(0, 0), PtInt64(2, 0)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(1, 4), PtInt64(2, 4)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(0, 3), PtInt64(3, 3)), ShouldBeFalse) // should be false
		So(rect.IntersectionWithLine(PtInt64(1, 3), PtInt64(2, 4)), ShouldBeFalse) // should be false
	})
}
