// Code generated by gotemplate. DO NOT EDIT.

package smap

import (
	. "github.com/smartystreets/goconvey/convey"

	"testing"
)

func TestSMapInt32String(t *testing.T) {
	Convey("test sync array", t, func() {
		tr := NewInt32String()
		So(tr.Len(), ShouldEqual, 0)
		So(tr.IsEmpty(), ShouldBeTrue)
		tr.Set(__formatKTypeToInt32String(1), __formatVTypeToInt32String(1))
		So(tr.Len(), ShouldEqual, 1)

		tr.Set(__formatKTypeToInt32String(1), __formatVTypeToInt32String(2))
		So(tr.Len(), ShouldEqual, 1)
		tr.Set(__formatKTypeToInt32String(2), __formatVTypeToInt32String(2))
		So(tr.Len(), ShouldEqual, 2)

		So(tr.Keys(), ShouldContain, __formatKTypeToInt32String(1))
		So(tr.Keys(), ShouldContain, __formatKTypeToInt32String(2))

		So(tr.GetAll(), ShouldContainKey, __formatKTypeToInt32String(1))
		So(tr.GetAll(), ShouldContainKey, __formatKTypeToInt32String(2))

		tr.Clear()
		So(tr.Len(), ShouldEqual, 0)

		tr.Set(__formatKTypeToInt32String(1), __formatVTypeToInt32String(2))
		tr.Set(__formatKTypeToInt32String(2), __formatVTypeToInt32String(2))
		So(func() {
			tr.ClearWithFuncLock(func(key int32, val string) {
				return
			})
		}, ShouldNotPanic)

		tr.Set(__formatKTypeToInt32String(1), __formatVTypeToInt32String(1))
		tr.Set(__formatKTypeToInt32String(2), __formatVTypeToInt32String(2))
		tr.Set(__formatKTypeToInt32String(3), __formatVTypeToInt32String(3))
		tr.Set(__formatKTypeToInt32String(4), __formatVTypeToInt32String(4))
		mk := []int32{__formatKTypeToInt32String(1), __formatKTypeToInt32String(2), __formatKTypeToInt32String(3)}
		m := tr.MGet(mk...)
		for _, k := range mk {
			So(m, ShouldContainKey, k)
		}

		tr2 := NewInt32String()
		tr2.MSet(m)
		So(tr2.Len(), ShouldEqual, len(mk))

		So(tr2.SetNX(__formatKTypeToInt32String(5), __formatVTypeToInt32String(5)), ShouldBeTrue)
		So(tr2.SetNX(__formatKTypeToInt32String(1), __formatVTypeToInt32String(5)), ShouldBeFalse)

		So(func() {
			tr2.LockFuncWithKey(__formatKTypeToInt32String(5), func(shardData map[int32]string) {
				return
			})
		}, ShouldNotPanic)
		So(func() {
			tr2.RLockFuncWithKey(__formatKTypeToInt32String(5), func(shardData map[int32]string) {
				return
			})
		}, ShouldNotPanic)
		So(func() {
			tr2.LockFunc(func(shardData map[int32]string) {
				return
			})
		}, ShouldNotPanic)
		So(func() {
			tr2.RLockFunc(func(shardData map[int32]string) {
				return
			})
		}, ShouldNotPanic)

		dfv := __formatVTypeToInt32String(1)
		r, ret := tr2.GetOrSetFunc(__formatKTypeToInt32String(1), func(key int32) string {
			return dfv
		})
		So(r, ShouldEqual, dfv)
		So(ret, ShouldBeFalse)
		r, ret = tr2.GetOrSetFuncLock(__formatKTypeToInt32String(1), func(key int32) string {
			return dfv
		})
		So(r, ShouldEqual, dfv)
		So(ret, ShouldBeFalse)

		_, ret = tr2.GetOrSet(__formatKTypeToInt32String(1), __formatVTypeToInt32String(1))
		So(ret, ShouldBeFalse)
		r, ret = tr2.GetOrSet(__formatKTypeToInt32String(10), __formatVTypeToInt32String(10))

		So(ret, ShouldBeTrue)
	})
}
