// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package goformat

import (
	"sync/atomic"
	"unsafe"
)

// Options should use NewOptions to initialize it
type Options struct {
	Fragment          bool `xconf:"fragment" usage:"允许解析源文件片段代码"`
	AllErrors         bool `xconf:"all_errors" usage:"打印所有的语法错误到标准输出。如果不使用此标记，则只会打印不同行的前10个错误"`
	RemoveBareReturns bool `xconf:"remove_bare_returns" usage:"移除无效的return"`
}

// NewOptions new Options
func NewOptions(opts ...Option) *Options {
	cc := newDefaultOptions()
	for _, opt := range opts {
		opt(cc)
	}
	if watchDogOptions != nil {
		watchDogOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option and return the old ones
// sample:
// old := cc.ApplyOption(WithTimeout(time.Second))
// defer cc.ApplyOption(old...)
func (cc *Options) ApplyOption(opts ...Option) []Option {
	var previous []Option
	for _, opt := range opts {
		previous = append(previous, opt(cc))
	}
	return previous
}

// Option option func
type Option func(cc *Options) Option

// WithFragment 允许解析源文件片段代码
func WithFragment(v bool) Option {
	return func(cc *Options) Option {
		previous := cc.Fragment
		cc.Fragment = v
		return WithFragment(previous)
	}
}

// WithAllErrors 打印所有的语法错误到标准输出。如果不使用此标记，则只会打印不同行的前10个错误
func WithAllErrors(v bool) Option {
	return func(cc *Options) Option {
		previous := cc.AllErrors
		cc.AllErrors = v
		return WithAllErrors(previous)
	}
}

// WithRemoveBareReturns 移除无效的return
func WithRemoveBareReturns(v bool) Option {
	return func(cc *Options) Option {
		previous := cc.RemoveBareReturns
		cc.RemoveBareReturns = v
		return WithRemoveBareReturns(previous)
	}
}

// InstallOptionsWatchDog the installed func will called when NewOptions  called
func InstallOptionsWatchDog(dog func(cc *Options)) { watchDogOptions = dog }

// watchDogOptions global watch dog
var watchDogOptions func(cc *Options)

// newDefaultOptions new default Options
func newDefaultOptions() *Options {
	cc := &Options{}

	for _, opt := range [...]Option{
		WithFragment(false),
		WithAllErrors(false),
		WithRemoveBareReturns(false),
	} {
		opt(cc)
	}

	return cc
}

// AtomicSetFunc used for XConf
func (cc *Options) AtomicSetFunc() func(interface{}) { return AtomicOptionsSet }

// atomicOptions global *Options holder
var atomicOptions unsafe.Pointer

// onAtomicOptionsSet global call back when  AtomicOptionsSet called by XConf.
// use OptionsInterface.ApplyOption to modify the updated cc
// if passed in cc not valid, then return false, cc will not set to atomicOptions
var onAtomicOptionsSet func(cc OptionsInterface) bool

// InstallCallbackOnAtomicOptionsSet install callback
func InstallCallbackOnAtomicOptionsSet(callback func(cc OptionsInterface) bool) {
	onAtomicOptionsSet = callback
}

// AtomicOptionsSet atomic setter for *Options
func AtomicOptionsSet(update interface{}) {
	cc := update.(*Options)
	if onAtomicOptionsSet != nil && !onAtomicOptionsSet(cc) {
		return
	}
	atomic.StorePointer(&atomicOptions, (unsafe.Pointer)(cc))
}

// AtomicOptions return atomic *OptionsVisitor
func AtomicOptions() OptionsVisitor {
	current := (*Options)(atomic.LoadPointer(&atomicOptions))
	if current == nil {
		defaultOne := newDefaultOptions()
		if watchDogOptions != nil {
			watchDogOptions(defaultOne)
		}
		atomic.CompareAndSwapPointer(&atomicOptions, nil, (unsafe.Pointer)(defaultOne))
		return (*Options)(atomic.LoadPointer(&atomicOptions))
	}
	return current
}

// all getter func
func (cc *Options) GetFragment() bool          { return cc.Fragment }
func (cc *Options) GetAllErrors() bool         { return cc.AllErrors }
func (cc *Options) GetRemoveBareReturns() bool { return cc.RemoveBareReturns }

// OptionsVisitor visitor interface for Options
type OptionsVisitor interface {
	GetFragment() bool
	GetAllErrors() bool
	GetRemoveBareReturns() bool
}

// OptionsInterface visitor + ApplyOption interface for Options
type OptionsInterface interface {
	OptionsVisitor
	ApplyOption(...Option) []Option
}
