// Code generated by gotemplate. DO NOT EDIT.

// syncmap 提供了一个同步的映射实现，允许安全并发的访问
package syncmap

import (
	"errors"

	. "github.com/smartystreets/goconvey/convey"

	"testing"
)

func TestIntUint16(t *testing.T) {
	Convey("test sync map", t, func() {
		for _, tr := range []*IntUint16{NewIntUint16()} {
			So(tr.Len(), ShouldBeZeroValue)
			var k, v = __formatKTypeToIntUint16(3), __formatVTypeToIntUint16(4)
			So(tr.Len(), ShouldEqual, 0)
			tr.Store(k, v)
			v1, ok := tr.Load(k)
			So(ok, ShouldBeTrue)
			So(v1, ShouldEqual, v)

			So(tr.Keys(), ShouldResemble, []int{__formatKTypeToIntUint16(3)})
			So(tr.Get(__formatKTypeToIntUint16(3)), ShouldEqual, __formatVTypeToIntUint16(4))
			So(tr.Contains(__formatKTypeToIntUint16(3)), ShouldBeTrue)

			tr.Store(__formatKTypeToIntUint16(4), __formatVTypeToIntUint16(5))
			tr.Store(__formatKTypeToIntUint16(5), __formatVTypeToIntUint16(6))
			ol := tr.Len()
			tr.DeleteMultiple(__formatKTypeToIntUint16(4), __formatKTypeToIntUint16(5))
			So(tr.Len(), ShouldEqual, ol-2)

			ol = tr.Len()
			tr.Store(__formatKTypeToIntUint16(4), __formatVTypeToIntUint16(5))
			tr.Store(__formatKTypeToIntUint16(5), __formatVTypeToIntUint16(6))
			vl, ok := tr.LoadAndDelete(__formatKTypeToIntUint16(4))
			So(vl, ShouldEqual, __formatVTypeToIntUint16(5))
			So(ok, ShouldBeTrue)
			So(tr.Len(), ShouldEqual, ol+1)

			tr.Store(__formatKTypeToIntUint16(4), __formatVTypeToIntUint16(5))
			fge := []func(key int, cf func(key int) (uint16, error)) (value uint16, loaded bool, err error){tr.GetOrSetFuncErrorLock}
			defv, defv2 := __formatVTypeToIntUint16(6), __formatVTypeToIntUint16(7)
			for _, f := range fge {
				v, l, e := f(__formatKTypeToIntUint16(6), func(key int) (uint16, error) {
					return defv, nil
				})
				So(v, ShouldEqual, defv)
				So(l, ShouldBeFalse)
				So(e, ShouldBeNil)

				v, l, e = f(__formatKTypeToIntUint16(7), func(key int) (uint16, error) {
					return defv2, errors.New("")
				})
				So(v, ShouldEqual, defv2)
				So(l, ShouldBeFalse)
				So(e, ShouldNotBeNil)
			}
			fg := []func(key int, cf func(key int) uint16) (value uint16, loaded bool){tr.GetOrSetFuncLock}
			for _, f := range fg {
				v, l := f(__formatKTypeToIntUint16(7), func(key int) uint16 {
					return defv2
				})
				So(v, ShouldEqual, defv2)
				So(l, ShouldBeFalse)
			}

			v, ok = tr.LoadOrStore(__formatKTypeToIntUint16(8), __formatVTypeToIntUint16(9))
			So(v, ShouldEqual, __formatVTypeToIntUint16(9))
			So(ok, ShouldBeFalse)

			So(func() {
				tr.Range(func(key int, value uint16) bool {
					return true
				})
			}, ShouldNotPanic)

		}
	})
}
