// Code generated by gotemplate. DO NOT EDIT.

package syncmap

import (
	. "github.com/smartystreets/goconvey/convey"

	"testing"
)

func TestInt16Any(t *testing.T) {
	Convey("test sync map", t, func() {
		for _, tr := range []*Int16Any{NewInt16Any()} {
			So(tr.Len(), ShouldBeZeroValue)
			var k, v = __formatKTypeToInt16Any(3), __formatVTypeToInt16Any(4)
			So(tr.Len(), ShouldEqual, 0)
			tr.Store(k, v)
			v1, ok := tr.Load(k)
			So(ok, ShouldBeTrue)
			So(v1, ShouldEqual, v)
		}
	})
}
