// Code generated by gotemplate. DO NOT EDIT.

package syncmap

import (
	"sort"
	"strconv"
	"sync"
)

//template type SyncMap(KType,VType)

type IntInt32 struct {
	sm     sync.Map
	locker sync.RWMutex
}

func NewIntInt32() *IntInt32 {
	return &IntInt32{}
}

func (s *IntInt32) Keys() (ret []int) {
	s.sm.Range(func(key, value interface{}) bool {
		ret = append(ret, key.(int))
		return true
	})
	return ret
}

func (s *IntInt32) Len() (c int) {
	s.sm.Range(func(key, value interface{}) bool {
		c++
		return true
	})
	return c
}

func (s *IntInt32) Contains(key int) (ok bool) {
	_, ok = s.Load(key)
	return
}

func (s *IntInt32) Get(key int) (value int32) {
	value, _ = s.Load(key)
	return
}

func (s *IntInt32) Load(key int) (value int32, loaded bool) {
	if v, ok := s.sm.Load(key); ok {
		return v.(int32), true
	}
	return
}
func (s *IntInt32) DeleteMultiple(keys ...int) {
	for _, k := range keys {
		s.sm.Delete(k)
	}
}
func (s *IntInt32) Clear() {
	s.sm.Range(func(key, value interface{}) bool {
		s.sm.Delete(key)
		return true
	})
}
func (s *IntInt32) Delete(key int)           { s.sm.Delete(key) }
func (s *IntInt32) Store(key int, val int32) { s.sm.Store(key, val) }
func (s *IntInt32) LoadAndDelete(key int) (value int32, loaded bool) {
	if v, ok := s.sm.LoadAndDelete(key); ok {
		return v.(int32), true
	}
	return
}
func (s *IntInt32) GetOrSetFuncErrorLock(key int, cf func(key int) (int32, error)) (value int32, loaded bool, err error) {
	return s.LoadOrStoreFuncErrorLock(key, cf)
}

func (s *IntInt32) LoadOrStoreFuncErrorLock(key int, cf func(key int) (int32, error)) (value int32, loaded bool, err error) {
	if v, ok := s.Load(key); ok {
		return v, true, nil
	}
	s.locker.Lock()
	defer s.locker.Unlock()
	// 再次重试，如果获取到则直接返回
	if v, ok := s.Load(key); ok {
		return v, true, nil
	}
	value, err = cf(key)
	if err != nil {
		return value, false, err
	}
	s.Store(key, value)
	return value, false, nil
}

func (s *IntInt32) GetOrSetFuncLock(key int, cf func(key int) int32) (value int32, loaded bool) {
	return s.LoadOrStoreFuncLock(key, cf)
}

func (s *IntInt32) LoadOrStoreFuncLock(key int, cf func(key int) int32) (value int32, loaded bool) {
	value, loaded, _ = s.LoadOrStoreFuncErrorLock(key, func(key int) (int32, error) {
		return cf(key), nil
	})
	return value, loaded
}

func (s *IntInt32) LoadOrStore(key int, val int32) (int32, bool) {
	actual, ok := s.sm.LoadOrStore(key, val)
	return actual.(int32), ok
}

func (s *IntInt32) Range(f func(key int, value int32) bool) {
	s.sm.Range(func(k, v interface{}) bool {
		return f(k.(int), v.(int32))
	})
}

func (s *IntInt32) RangeDeterministic(f func(key int, value int32) bool, sortableGetter func([]int) sort.Interface) {
	var keys []int
	s.sm.Range(func(key, value interface{}) bool {
		keys = append(keys, key.(int))
		return true
	})
	sort.Sort(sortableGetter(keys))
	for _, k := range keys {
		if v, ok := s.Load(k); ok {
			if !f(k, v) {
				break
			}
		}
	}
}

//template format
var __formatKTypeToIntInt32 = func(i interface{}) int {
	switch ii := i.(type) {
	case int:
		return int(ii)
	case int8:
		return int(ii)
	case int16:
		return int(ii)
	case int32:
		return int(ii)
	case int64:
		return int(ii)
	case uint:
		return int(ii)
	case uint8:
		return int(ii)
	case uint16:
		return int(ii)
	case uint32:
		return int(ii)
	case uint64:
		return int(ii)
	case float32:
		return int(ii)
	case float64:
		return int(ii)
	case string:
		iv, err := strconv.ParseInt(ii, 10, 64)
		if err != nil {
			panic(err)
		}
		return int(iv)
	default:
		panic("unknown type")
	}
}

//template format
var __formatVTypeToIntInt32 = func(i interface{}) int32 {
	switch ii := i.(type) {
	case int:
		return int32(ii)
	case int8:
		return int32(ii)
	case int16:
		return int32(ii)
	case int32:
		return int32(ii)
	case int64:
		return int32(ii)
	case uint:
		return int32(ii)
	case uint8:
		return int32(ii)
	case uint16:
		return int32(ii)
	case uint32:
		return int32(ii)
	case uint64:
		return int32(ii)
	case float32:
		return int32(ii)
	case float64:
		return int32(ii)
	case string:
		iv, err := strconv.ParseInt(ii, 10, 64)
		if err != nil {
			panic(err)
		}
		return int32(iv)
	default:
		panic("unknown type")
	}
}
