// Code generated by gotemplate. DO NOT EDIT.

package syncmap

import (
	"sort"
	"strconv"
	"sync"
)

//template type SyncMap(KType,VType)

type IntUint struct {
	sm     sync.Map
	locker sync.RWMutex
}

func NewIntUint() *IntUint {
	return &IntUint{}
}

func (s *IntUint) Keys() (ret []int) {
	s.sm.Range(func(key, value interface{}) bool {
		ret = append(ret, key.(int))
		return true
	})
	return ret
}

func (s *IntUint) Len() (c int) {
	s.sm.Range(func(key, value interface{}) bool {
		c++
		return true
	})
	return c
}

func (s *IntUint) Contains(key int) (ok bool) {
	_, ok = s.Load(key)
	return
}

func (s *IntUint) Get(key int) (value uint) {
	value, _ = s.Load(key)
	return
}

func (s *IntUint) Load(key int) (value uint, loaded bool) {
	if v, ok := s.sm.Load(key); ok {
		return v.(uint), true
	}
	return
}
func (s *IntUint) DeleteMultiple(keys ...int) {
	for _, k := range keys {
		s.sm.Delete(k)
	}
}
func (s *IntUint) Clear() {
	s.sm.Range(func(key, value interface{}) bool {
		s.sm.Delete(key)
		return true
	})
}
func (s *IntUint) Delete(key int)          { s.sm.Delete(key) }
func (s *IntUint) Store(key int, val uint) { s.sm.Store(key, val) }
func (s *IntUint) LoadAndDelete(key int) (value uint, loaded bool) {
	if v, ok := s.sm.LoadAndDelete(key); ok {
		return v.(uint), true
	}
	return
}
func (s *IntUint) GetOrSetFuncErrorLock(key int, cf func(key int) (uint, error)) (value uint, loaded bool, err error) {
	return s.LoadOrStoreFuncErrorLock(key, cf)
}

func (s *IntUint) LoadOrStoreFuncErrorLock(key int, cf func(key int) (uint, error)) (value uint, loaded bool, err error) {
	if v, ok := s.Load(key); ok {
		return v, true, nil
	}
	s.locker.Lock()
	defer s.locker.Unlock()
	// 再次重试，如果获取到则直接返回
	if v, ok := s.Load(key); ok {
		return v, true, nil
	}
	value, err = cf(key)
	if err != nil {
		return value, false, err
	}
	s.Store(key, value)
	return value, false, nil
}

func (s *IntUint) GetOrSetFuncLock(key int, cf func(key int) uint) (value uint, loaded bool) {
	return s.LoadOrStoreFuncLock(key, cf)
}

func (s *IntUint) LoadOrStoreFuncLock(key int, cf func(key int) uint) (value uint, loaded bool) {
	value, loaded, _ = s.LoadOrStoreFuncErrorLock(key, func(key int) (uint, error) {
		return cf(key), nil
	})
	return value, loaded
}

func (s *IntUint) LoadOrStore(key int, val uint) (uint, bool) {
	actual, ok := s.sm.LoadOrStore(key, val)
	return actual.(uint), ok
}

func (s *IntUint) Range(f func(key int, value uint) bool) {
	s.sm.Range(func(k, v interface{}) bool {
		return f(k.(int), v.(uint))
	})
}

func (s *IntUint) RangeDeterministic(f func(key int, value uint) bool, sortableGetter func([]int) sort.Interface) {
	var keys []int
	s.sm.Range(func(key, value interface{}) bool {
		keys = append(keys, key.(int))
		return true
	})
	sort.Sort(sortableGetter(keys))
	for _, k := range keys {
		if v, ok := s.Load(k); ok {
			if !f(k, v) {
				break
			}
		}
	}
}

//template format
var __formatKTypeToIntUint = func(i interface{}) int {
	switch ii := i.(type) {
	case int:
		return int(ii)
	case int8:
		return int(ii)
	case int16:
		return int(ii)
	case int32:
		return int(ii)
	case int64:
		return int(ii)
	case uint:
		return int(ii)
	case uint8:
		return int(ii)
	case uint16:
		return int(ii)
	case uint32:
		return int(ii)
	case uint64:
		return int(ii)
	case float32:
		return int(ii)
	case float64:
		return int(ii)
	case string:
		iv, err := strconv.ParseInt(ii, 10, 64)
		if err != nil {
			panic(err)
		}
		return int(iv)
	default:
		panic("unknown type")
	}
}

//template format
var __formatVTypeToIntUint = func(i interface{}) uint {
	switch ii := i.(type) {
	case int:
		return uint(ii)
	case int8:
		return uint(ii)
	case int16:
		return uint(ii)
	case int32:
		return uint(ii)
	case int64:
		return uint(ii)
	case uint:
		return uint(ii)
	case uint8:
		return uint(ii)
	case uint16:
		return uint(ii)
	case uint32:
		return uint(ii)
	case uint64:
		return uint(ii)
	case float32:
		return uint(ii)
	case float64:
		return uint(ii)
	case string:
		iv, err := strconv.ParseUint(ii, 10, 64)
		if err != nil {
			panic(err)
		}
		return uint(iv)
	default:
		panic("unknown type")
	}
}
