// Code generated by gotemplate. DO NOT EDIT.

package syncmap

import (
	. "github.com/smartystreets/goconvey/convey"

	"testing"
)

func TestInt8Int64(t *testing.T) {
	Convey("test sync map", t, func() {
		for _, tr := range []*Int8Int64{NewInt8Int64()} {
			So(tr.Len(), ShouldBeZeroValue)
			var k, v = __formatKTypeToInt8Int64(3), __formatVTypeToInt8Int64(4)
			So(tr.Len(), ShouldEqual, 0)
			tr.Store(k, v)
			v1, ok := tr.Load(k)
			So(ok, ShouldBeTrue)
			So(v1, ShouldEqual, v)
		}
	})
}
