// Code generated by gotemplate. DO NOT EDIT.

// syncmap 提供了一个同步的映射实现，允许安全并发的访问
package syncmap

import (
	"errors"

	. "github.com/smartystreets/goconvey/convey"

	"testing"
)

func TestAnyAny(t *testing.T) {
	Convey("test sync map", t, func() {
		for _, tr := range []*AnyAny{NewAnyAny()} {
			So(tr.Len(), ShouldBeZeroValue)
			var k, v = __formatKTypeToAnyAny(3), __formatVTypeToAnyAny(4)
			So(tr.Len(), ShouldEqual, 0)
			tr.Store(k, v)
			v1, ok := tr.Load(k)
			So(ok, ShouldBeTrue)
			So(v1, ShouldEqual, v)

			So(tr.Keys(), ShouldResemble, []interface{}{__formatKTypeToAnyAny(3)})
			So(tr.Get(__formatKTypeToAnyAny(3)), ShouldEqual, __formatVTypeToAnyAny(4))
			So(tr.Contains(__formatKTypeToAnyAny(3)), ShouldBeTrue)

			tr.Store(__formatKTypeToAnyAny(4), __formatVTypeToAnyAny(5))
			tr.Store(__formatKTypeToAnyAny(5), __formatVTypeToAnyAny(6))
			ol := tr.Len()
			tr.DeleteMultiple(__formatKTypeToAnyAny(4), __formatKTypeToAnyAny(5))
			So(tr.Len(), ShouldEqual, ol-2)

			ol = tr.Len()
			tr.Store(__formatKTypeToAnyAny(4), __formatVTypeToAnyAny(5))
			tr.Store(__formatKTypeToAnyAny(5), __formatVTypeToAnyAny(6))
			vl, ok := tr.LoadAndDelete(__formatKTypeToAnyAny(4))
			So(vl, ShouldEqual, __formatVTypeToAnyAny(5))
			So(ok, ShouldBeTrue)
			So(tr.Len(), ShouldEqual, ol+1)

			tr.Store(__formatKTypeToAnyAny(4), __formatVTypeToAnyAny(5))
			fge := []func(key interface{}, cf func(key interface{}) (interface{}, error)) (value interface{}, loaded bool, err error){tr.GetOrSetFuncErrorLock}
			defv, defv2 := __formatVTypeToAnyAny(6), __formatVTypeToAnyAny(7)
			for _, f := range fge {
				v, l, e := f(__formatKTypeToAnyAny(6), func(key interface{}) (interface{}, error) {
					return defv, nil
				})
				So(v, ShouldEqual, defv)
				So(l, ShouldBeFalse)
				So(e, ShouldBeNil)

				v, l, e = f(__formatKTypeToAnyAny(7), func(key interface{}) (interface{}, error) {
					return defv2, errors.New("")
				})
				So(v, ShouldEqual, defv2)
				So(l, ShouldBeFalse)
				So(e, ShouldNotBeNil)
			}
			fg := []func(key interface{}, cf func(key interface{}) interface{}) (value interface{}, loaded bool){tr.GetOrSetFuncLock}
			for _, f := range fg {
				v, l := f(__formatKTypeToAnyAny(7), func(key interface{}) interface{} {
					return defv2
				})
				So(v, ShouldEqual, defv2)
				So(l, ShouldBeFalse)
			}

			v, ok = tr.LoadOrStore(__formatKTypeToAnyAny(8), __formatVTypeToAnyAny(9))
			So(v, ShouldEqual, __formatVTypeToAnyAny(9))
			So(ok, ShouldBeFalse)

			So(func() {
				tr.Range(func(key interface{}, value interface{}) bool {
					return true
				})
			}, ShouldNotPanic)

		}
	})
}
