// Code generated by gotemplate. DO NOT EDIT.

package sarray

import (
	. "github.com/smartystreets/goconvey/convey"

	"testing"
)

func TestUint16(t *testing.T) {
	Convey("test sync set", t, func() {
		for _, tr := range []*Uint16{NewUint16(), NewSyncUint16()} {
			So(tr.Size(), ShouldBeZeroValue)
			var e0 = __formatToUint16(3)
			tr.Add(e0)
			So(tr.Size(), ShouldEqual, 1)
			tr.Add(e0)
			So(tr.Size(), ShouldEqual, 1)
		}
	})
}
